lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Microblog.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/posts", PostController

    post "/session", SessionController, :create
    delete "/session", SessionController, :delete

    get "/feed", PageController, :feed
  end

  # Other scopes may use custom stacks.
  # scope "/api", MicroblogWeb do
  #   pipe_through :api
  # end
end

lib/microblog_web/templates/page/feed.html.eex
<%= if @current_user do %>
  <div class="row">
    <div class="col">
      <%= render MicroblogWeb.PostView, "form.html",
          Map.put(assigns, :action, post_path(@conn, :create)) %>
    </div>
  </div>
<% end %>

<h1>Your Feed</h1>

<%= Enum.map @posts, fn post -> %>
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h6 class="card-title"><%= post.user.name %></h6>
        <p><%= post.body %></p>
      </div>
    </div>
  </div>
</div>
<% end %>

lib/microblog_web/templates/page/index.html.eex
<div class="row">
    <div class="col">

        <h1>Log In</h1>
        <%= form_tag("/session", method: :post) do %>
        <div class="form-group">
            Email
            <input type="email" name="email" placeholder="user@example.com" >
        </div>
        <div class="form-group">
            <button class="btn btn-primary">Log in</button>
            <%= link "Register", to: user_path(@conn, :new) %>
        </div>
        <% end %>

    </div>
</div>